[package]
name = "hview-front"
version = "0.1.0"
authors = ["Steven Bower <bowerblu@gmail.com>"]
edition = "2018"

[dependencies]
yew = "0.18"
yew-router = "0.15"
serde = "1.0"
anyhow = "1.0"
url = "2.2.2"
